# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mywindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 499)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.VLayoutButtonTable = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VLayoutButtonTable.setContentsMargins(0, 0, 0, 0)
        self.VLayoutButtonTable.setObjectName("VLayoutButtonTable")
        self.labelTable = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTable.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTable.setObjectName("labelTable")
        self.VLayoutButtonTable.addWidget(self.labelTable)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(75)
        self.VLayoutButtonTable.addWidget(self.tableWidget)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.VLayoutButtonTable.addWidget(self.pushButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(280, 0, 521, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.chartWidget = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.chartWidget.setContentsMargins(0, 0, 0, 0)
        self.chartWidget.setObjectName("chartWidget")
        self.labelChart = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelChart.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelChart.setObjectName("labelChart")
        self.chartWidget.addWidget(self.labelChart)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Excel = QtWidgets.QAction(MainWindow)
        self.action_Excel.setObjectName("action_Excel")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Print = QtWidgets.QAction(MainWindow)
        self.action_Print.setObjectName("action_Print")
        self.menu.addAction(self.action_Excel)
        self.menu.addAction(self.action_Print)
        self.menu.addSeparator()
        self.menu.addAction(self.action_Exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTable.setText(_translate("MainWindow", "Ручной ввод"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ток, А"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "0.5"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "10P"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("MainWindow", "0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Построить график"))
        self.labelChart.setText(_translate("MainWindow", "График ВАХ"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action_Excel.setText(_translate("MainWindow", "Загрузить Excel"))
        self.action_Exit.setText(_translate("MainWindow", "Выход"))
        self.action_Print.setText(_translate("MainWindow", "Печать"))

